[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run lint",
  "npm run test:smoke",
  "npx prisma generate",
  "npx next build"
]

[start]
cmd = "npx prisma migrate deploy && npm start"
